#include <iostream>
#include <cstring>
#include <cstdlib>
#include <cstdint>
#include <vector>
#include <string>
#include <stdexcept>
#include "../h/cpu.h"
#include "../h/instruction.h"
#include "../h/utils.h"